from setuptools import setup, find_packages

setup(
    name="s3_utils",
    version="0.2",
    author="Visapick Backend team",
    url="https://github.com/Visapick-Team/S3-utils",
    description="S3 storge object updating in python",
    long_description="Using this package you can upload your files into S3 buckets",
    keywords="s3, bucket, storage",
    python_requires=">=3.8, <4",
    packages=["s3_utils"],
    install_requires=[
        "boto3>=1.28.3",
        "botocore>=1.31.3",
        "exceptiongroup>=1.1.2",
        "idna>=3.4",
        "jmespath>=1.0.1",
        "pydantic>=1.10.11",
        "python-dateutil>=2.8.2",
        "s3transfer>=0.6.1",
        "six>=1.16.0",
        "sniffio>=1.3.0",
        "urllib3>=1.26.16",
    ],
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Developers",
        "Topic :: Software Development :: Build Tools",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3 :: Only",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
)
